### ISSUE TITLE
Docker for Mac Audio

### ISSUE THREAD

**Issue by btotharye** [MycroftAI/docker-mycroft#15]
Seems like there might be an issue with using Docker for Mac and how OSX audio devices work.  Still investigating.

**Comment by rhelmer** [comment]
I don't think it's currently possible to forward the sound device from the Linux docker image to the macOS host, but it's possible to install PulseAudio (using Homebrew) and forwarding that over the network - see https://stackoverflow.com/questions/40136606/how-to-expose-audio-from-docker-container-to-a-mac

**Comment by btotharye** [comment]
Thanks I'll take a look

**Comment by 8enmann** [comment]
Would be great to have instructions on how to run this on Mac if anyone figures it out!

**Comment by btotharye** [comment]
Yea I'm working on it, I'll document it

**Comment by Mn0491** [comment]
@btotharye have you figured out how to get it working on a mac?

**Comment by btotharye** [comment]
I'm still working on getting the base image finished up using the apt repo's, etc.  Still working with the team to work through those issues.  Once the image is production ready and stable I will then turn efforts into this. 

Thanks

**Comment by BenjaminHCCarr** [comment]
The short answer is that this is a shortcoming of docker on OSX and BSD in general. Docker relies on a hard coded `/dev/audio` to do sound output. That said. It works fine with the Android app.

That said I am trying to do a native install using Homebrew:
Tap: `brew tap benjaminhccarr/tap`
Formula: https://github.com/BenjaminHCCarr/homebrew-tap/blob/master/Formula/mycroft-core.rb

I started with the RPi code: https://github.com/MycroftAI/enclosure-picroft

So you can see I am a bit behind... the idea was to get known working going first, but as we are now 9 revisions behind `-core` I may start unpinning things!

The original (failing) RPi build is at: https://github.com/BenjaminHCCarr/homebrew-tap/blob/master/Formula/mycroft-core.rb-Pinned where all the repos/deps were pinned... this broke badly. I was trying to bump as few as possible from a known good config.

The script at: https://github.com/BenjaminHCCarr/homebrew-tap/blob/master/requirements_to_resources.sh allows you to change resources.txt into Homebrew requirements. This was tedious; this generates 98% of the deps with `sha`'s but occasionally fails on weird compression schemes.

There was talk of a pure python install, but that gets ugly too; people talked about cassandra and anaconda.

At the moment I think the best `native` solution is homebrew. Plus 78.62% of the work is in the repo, I just need time/testers to sort things.

**Comment by btotharye** [comment]
going to close out this issue for now since I don't think it is anything we can really do atm here.
