### ISSUE TITLE
Freezes during docker build

### ISSUE THREAD

**Issue by ElCuboNegro** [MycroftAI/docker-mycroft#52]
The docker build freezes at this point, it seems like there is not input from the keyboard. I suggest to automate the best responses at this point or include the configuration on the dockerfile

![Anotación 2019-04-28 040111](https://user-images.githubusercontent.com/5524219/56861818-5bda6500-696a-11e9-9f44-adc66eec561e.png)

**Comment by forslund** [comment]
Hi, I think this can be worked around by adding the environment variable IS_TRAVIS to the build step.

The docker-mycroft project was community led but currently I don't think there's anyone maintaining it. If you're experienced with docker and like to help you're welcome to help out.

**Comment by machinekoder** [comment]
Create `.dev_opts.json` and add `COPY .dev_opts.json /opt/` to the `Dockerfile`

```json
{"use_branch": "master", "auto_update": true}
```

**Comment by TheLastProject** [comment]
Fixed in b18034cf85931d0d70c51e02a7b7d785b2cc5305.
