### ISSUE TITLE
Add instructions for setting up TTS

### ISSUE THREAD

**Issue by jpsamaroo** [MycroftAI/docker-mycroft#57]
In order to make TTS work on docker-mycroft, I had to first use `scripts/install-mimic.sh`, and the add the created directory to my `PATH`. It would be great if this were mentioned in the README.

**Comment by TheLastProject** [comment]
It seems better if the Docker image would do this itself. How would I be able to test if this works? The device I run Docker on sadly doesn't have any speaker.

**Comment by forslund** [comment]
I setup a mycroft-desktop packaging repo once. There was no real interest in the Mycroft-core package so that hasn't been maintained but there is a mimic package there for x86_64 (built on ubuntu 18.04) we could see if that works on the docker image?

**Comment by TheLastProject** [comment]
Sounds good to me but my issue is that I'll need to know how I can confirm it is working

**Comment by forslund** [comment]
The basics can be tests by invoking the mimic commandline and having it write a wav to disk. Ensuring audio out may be delegated to me / a community member. If that's good enough for you.

**Comment by TheLastProject** [comment]
Fixed by #58.
