### ISSUE TITLE
Config not stored in external value, need to reconnect to home.mycroft.ai after container restart

### ISSUE THREAD

**Issue by TheLastProject** [MycroftAI/docker-mycroft#59]
@forslund any clue which file(s) it puts all this stuff in? So I can update the instructions so people make this an external volume so it persists between reloads?

**Comment by forslund** [comment]
I think it's in the instructions already isn't it?

```
-v directory_on_local_machine:/root/.mycroft \
```

where directory_on_local_machine is the folder where the mycroft.conf and the identity/identity2.json (contains pairing information) is placed

Maybe needs to be highlighted...

**Comment by TheLastProject** [comment]
Oh nice, my Synology NAS messed up and forgot the container settings. Lovely. Thanks lol.
