### ISSUE TITLE
.dockerenv does not exist

### ISSUE THREAD

**Issue by pabsi** [MycroftAI/docker-mycroft#64]
Hi there,
the entrypoint for the docker container is `/opt/mycroft/startup.sh`, which then calls `start-mycroft.sh`. The latter script, has the following function:

```
function source-venv() {
    # Enter Python virtual environment, unless under Docker
    if [ ! -f "/.dockerenv" ] ; then
        source ${VIRTUALENV_ROOT}/bin/activate
    fi
}
```

Which will do not what is expected as `.dockerenv` does not exist:

```$ docker exec -it mycroft /bin/bash
(.venv) root@7c957415279a:/opt/mycroft# ls -la .dockerenv
ls: cannot access '.dockerenv': No such file or directory
```

I am not sure I am missing something, and this is why I raised an issue and not a PR.

Thank you for your hard work! :)

**Comment by TheLastProject** [comment]
Oh, nice find.

Currently, the container calls bin/activate itself, so we probably do need to call activate: https://github.com/MycroftAI/docker-mycroft/blob/b18034cf85931d0d70c51e02a7b7d785b2cc5305/startup.sh#L2

@forslund Any clue why this check exists in Mycroft core?

**Comment by pabsi** [comment]
Not sure if it is bad or not, I just happened to found that while trying to troubleshoot my Jabra 510 not working (it was before!!). I must have done something with pulse/alsa on the host :( 

I also _think_ the mounts needed for docker are more than the ones in the docs, but I'll confirm that later if that's the case, with a PR/issue.

Thanks again!

PS: super fast response! :open_mouth:

**Comment by pabsi** [comment]
On another note, is `dev_setup.sh` supposed to run too?
It tries to `chown` a pip directory and as a result of running container as root (inside) you get a ton of
`ownership of '/opt/mycroft/mycroft/dialog/__init__.py' retained as root:root`

**Comment by TheLastProject** [comment]
I'll be honest, I don't quite know. When I wanted to use this image it was broken so I just messed with it until it worked.

**Comment by forslund** [comment]
Not so super fast response from me...The .dockerenv check seems to have been added [here](https://github.com/MycroftAI/mycroft-core/commit/e48225417242c176006c51cb2b04650bd972567d#diff-538177abf8c3828b521b60947886da59) and it seems to be used to allow running the docker without a virtualenv setup. (installing everything into the docker container's global environment).

Imho the docker should either use the start-mycroft.sh with the venv like it does now, or install mycroft-core via pip and not use the start-mycroft-sh script at all.

From the next release of mycroft-core the chown checks will be quieted.

**Comment by pabsi** [comment]
Hey @forslund , still helpful response though.
I appreciate you 2 getting back to me.
I'll close this issue since as you say the `chown` commands will be quieted. Although IMHO the long term should be to install Mycroft Core in the docker env; I personally don't see much point of using a venv within docker.
Anyway, thanks, and closing issue!
