### ISSUE TITLE
configure not needed

### ISSUE THREAD

**Issue by allank** [MycroftAI/docker-mycroft#8]
The sphinx repo's call `configure` from the `autogen.sh` script, so the `configure` line is probably superfluous.

Haven't tested without it yet, but when I followed the `Dockerfile` steps manually I didn't need to include it.

**Comment by paulscott56** [comment]
I am a little reluctant to remove the configure line, as autotools should only really *create* the configure script. At some stage we may also want to pass in additional configure params, so would rather leave as is for now.

Closing for now, but feel free to re-open in future
