### ISSUE TITLE
HTTP 404: Not Found

### ISSUE THREAD

**Issue by hassanayoub1985** [MycroftAI/docker-mycroft#80]
**Describe the bug**
I run the docker on my machine, when Inavigate to machine_ip:8181 it shows this error:
Traceback (most recent call last):
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/tornado/web.py", line 1681, in _execute
    result = self.prepare()
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/tornado/web.py", line 2430, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found

**To Reproduce**
1. Go to 'http://143.198.230.254:8181/'
2. 2. See error

**Expected behavior**
Itexpectedto see the web interface of mycraft
**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: [e.g. Raspberry Pi, Mark 1, desktop]
 - OS: [e.g. Ubuntu, Picroft]
 - Mycroft-core version: [e.g. 20.08]
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**

Please think carefully about whether you have modified anything in Mycroft's code or configuration files.  If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

**Comment by krisgesling** [comment]
Hey there, port 8181 is the web socket interface for the Mycroft message bus. There is no http server providing a web page so visiting that url in a browser would fail.

More about the message bus here: 
https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-bus
